apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
      env  : ft_service
      app  : mysql
      owner: gdrive
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-deployment
    env  : ft_service
    owner: gdrive
spec:
  replicas: 1
  selector:
    matchLabels:
      project: mysql
  template:
    metadata:
      labels:
        project: mysql
    spec:
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
      containers:
      - name           : mysql
        image          : mysql:v1
        imagePullPolicy: Never
        ports          :
        - containerPort: 3306
        volumeMounts   :
        - mountPath: "/var/lib/mysql"
          name     : mysql-volume
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
      env  : ft_service
      app  : mysql
      owner: gdrive
spec:
  type: ClusterIP
  selector:
    project: mysql
  ports:
  - name      : http
    port      : 3306
    targetPort: 3306

