apiVersion: apps/v1
kind: Deployment
metadata:
    name : nginx-d
    labels:
        app: nginx
spec:
    # replicas: <number>
    # Whats pods to choose? #
    selector:
        # With labels: #
        matchLabels:
            project: main-nginx
    # Creating pods #
    template:
        metadata:
            labels:
                project: main-nginx
        spec:
            containers:
                - name : main-nginx
                  image: main-nginx:v1
                  ports:
                      - containerPort: 80
                      - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-s
    labels:
        env: nginx
# What pods ? #
spec:
    selector:
        project: main-nginx
    ports:
        - name       : app-listener
          protocol   : TCP
          # Port on LoadBalancer #
          port       : 443
          # Port on pod #
          targetPort : 443
    type: LoadBalancer
