apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app  : phpmyadmin
    env  : ft_services
    owner: gdrive
spec:
  replicas: 1
  selector:
    matchLabels:
      project: phpmyadmin
  template:
    metadata:
      labels:
        project: phpmyadmin
    spec:
      containers:
      - name           : phpmyadmin
        image          : phpmyadmin:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: phmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: services
  labels:
    app  : phpmyadmin
    env  : ft_services
    owner: gdrive
spec:
  type: LoadBalancer
  selector:
    project: phpmyadmin
  ports:
  - name      : http
    port      : 5000
    targetPort: 5000
